on: release
name: Build, Test, and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    - name: Test
      uses: actions/npm@master
      with:
        args: test
    - name: Publish
      uses: artemnovichkov/action-zem@master
      env:
        ZEM_TOKEN: ${{ secrets.ZEM_TOKEN }}
      with:
        args: publish
on: push
name: Run exec
jobs:
  build:
    name: Exec
    runs-on: macOS-latest
    steps:
    - name: Install npm
      uses: actions/npm@master
      with:
        args: install
    - name: Install zem
      uses: actions/npm@master
      with:
        args: install -g zem
    - name: Exec
      uses: actions/npm@master
      with:
        args: npm run exec
