on: push
name: Run tests
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-node@v1.4.1
      with:
        node-version: '10.x'
    - run: npm install -g zem
    - run: npm test
